=== Khodyko/trainingEpam/TasksEpam/src/Task3/resources/connect.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/connect"
	xmlns:tns="http://www.example.org/connect"
	elementFormDefault="qualified">
	<element name="tarifs">
		<complexType>
			<sequence>
				<element name="tarif" maxOccurs="unbounded">
					<complexType>
						<sequence>
							<element name="name" type="string" />
							<element name="operatorName" type="string" />
							<element name="payRoll">
								<simpleType>
									<restriction base="int">
										<minInclusive value="0" />
										<maxInclusive value="99" />
									</restriction>
								</simpleType>
							</element>

							<element name="callPrice">
								<complexType>
									<sequence>
										<element name="inNetCallCost">
											<simpleType>
												<restriction base="int">
													<minInclusive value="0" />
													<maxInclusive value="99" />
												</restriction>
											</simpleType>
										</element>
										<element name="outNetCallCost">
											<simpleType>
												<restriction base="int">
													<minInclusive value="0" />
													<maxInclusive value="99" />
												</restriction>
											</simpleType>
										</element>
										<element name="homePhoneCallCost">
											<simpleType>
												<restriction base="int">
													<minInclusive value="0" />
													<maxInclusive value="99" />
												</restriction>
											</simpleType>
										</element>
									</sequence>
								</complexType>
							</element>


							<element name="smsPrice">
								<simpleType>
									<restriction base="int">
										<minInclusive value="0" />
										<maxInclusive value="10" />
									</restriction>
								</simpleType>
							</element>
							<element name="parameters">
								<complexType>
									<sequence>
										<element name="lovelyNumber" minOccurs="0">
											<simpleType>
												<restriction base="string">
													<pattern value="\+375(29|33|44|25)[0-9]{7}" />
												</restriction>
											</simpleType>
										</element>
										<element name="tarificationTime">
											<simpleType>
												<restriction base="int">
													<enumeration value="12" />
													<enumeration value="60" />
												</restriction>
											</simpleType>
										</element>
										<element name="comingPay" type="positiveInteger" />
									</sequence>
								</complexType>
							</element>
						</sequence>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
</schema>

=== Khodyko/trainingEpam/TasksEpam/bin/Task3/company/connect.xml
<?xml version="1.0" encoding="UTF-8" ?>
<tarifs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.example.org/connect" xsi:schemaLocation="http://www.example.org/connect  connect.xsd">
    <tarif>
        <name>up</name>
        <operatorName>mts</operatorName>
        <payRoll>99</payRoll>

        <callPrice>
            <inNetCallCost>12</inNetCallCost>
            <outNetCallCost>12</outNetCallCost>
            <homePhoneCallCost>12</homePhoneCallCost>
        </callPrice>

        <smsPrice>1</smsPrice>
        <parameters>
            <lovelyNumber>+375292320038</lovelyNumber>
            <tarificationTime>12</tarificationTime>
            <comingPay>140</comingPay>
        </parameters>
    </tarif>
    <tarif>
        <name>plus</name>
        <operatorName>life</operatorName>
        <payRoll>99</payRoll>

        <callPrice>
            <inNetCallCost>12</inNetCallCost>
            <outNetCallCost>12</outNetCallCost>
            <homePhoneCallCost>12</homePhoneCallCost>
        </callPrice>

        <smsPrice>1</smsPrice>
        <parameters>
            <lovelyNumber>+375292320038</lovelyNumber>
            <tarificationTime>12</tarificationTime>
            <comingPay>140</comingPay>
        </parameters>
    </tarif>
    <tarif>
        <name>gogogo</name>
        <operatorName>velcom</operatorName>
        <payRoll>99</payRoll>

        <callPrice>
            <inNetCallCost>12</inNetCallCost>
            <outNetCallCost>12</outNetCallCost>
            <homePhoneCallCost>12</homePhoneCallCost>
        </callPrice>

        <smsPrice>1</smsPrice>
        <parameters>
            <lovelyNumber>+375292320038</lovelyNumber>
            <tarificationTime>12</tarificationTime>
            <comingPay>140</comingPay>
        </parameters>
    </tarif>
</tarifs>
